import { useState, useRef, useEffect } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface DocumentExportProps {
  transcript: string;
  summary: string;
  language: string;
  onClose: () => void;
}

export default function DocumentExport({ transcript, summary, language, onClose }: DocumentExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const documentRef = useRef<HTMLDivElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setShowExportMenu(false);
      }
    };

    if (showExportMenu) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showExportMenu]);

  const extractKeyPoints = (summaryText: string): string[] => {
    const lines = summaryText.split('\n').filter(line => line.trim());
    const keyPoints: string[] = [];
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.match(/^[-•*]\s/)) {
        keyPoints.push(trimmed.replace(/^[-•*]\s/, ''));
      } else if (trimmed.match(/^\d+\.\s/)) {
        keyPoints.push(trimmed.replace(/^\d+\.\s/, ''));
      } else if (trimmed.length > 10 && trimmed.length < 150) {
        keyPoints.push(trimmed);
      }
    }
    
    if (keyPoints.length === 0) {
      const sentences = summaryText.split(/[.!?]+/).filter(s => s.trim().length > 20);
      return sentences.slice(0, 5).map(s => s.trim());
    }
    
    return keyPoints.slice(0, 5);
  };

  const keyPoints = extractKeyPoints(summary);
  const wordCount = transcript.split(/\s+/).length;
  const readTime = Math.ceil(wordCount / 200);

  // Analyze conversation for pain points and lapses
  const analyzePainPoints = (text: string): string[] => {
    const painKeywords = ['problem', 'issue', 'difficult', 'challenge', 'struggle', 'concern', 'worry', 'frustrat', 'confus', 'unclear', 'hard', 'complicate'];
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 15);
    return sentences
      .filter(s => painKeywords.some(keyword => s.toLowerCase().includes(keyword)))
      .slice(0, 4)
      .map(s => s.trim());
  };

  const analyzeLapses = (text: string): number => {
    const shortSentences = text.split(/[.!?]+/).filter(s => s.trim().split(/\s+/).length < 3);
    return Math.min(Math.floor(shortSentences.length / 3), 5);
  };

  const calculateComprehension = (): number => {
    const avgWordLength = transcript.split(/\s+/).reduce((acc, word) => acc + word.length, 0) / wordCount;
    const sentenceCount = transcript.split(/[.!?]+/).filter(s => s.trim()).length;
    const avgSentenceLength = wordCount / sentenceCount;
    
    let score = 85;
    if (avgWordLength > 6) score -= 10;
    if (avgSentenceLength > 25) score -= 10;
    if (keyPoints.length < 3) score -= 5;
    
    return Math.max(60, Math.min(100, score));
  };

  const painPoints = analyzePainPoints(transcript + ' ' + summary);
  const conversationLapses = analyzeLapses(transcript);
  const comprehensionScore = calculateComprehension();

  const handleExportClick = (type: 'pdf' | 'jpg') => {
    setShowExportMenu(false);
    if (type === 'pdf') {
      exportToPDF();
    } else {
      exportToJPG();
    }
  };

  const exportToPDF = async () => {
    setIsExporting(true);

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      let yPosition = margin;

      // Helper function to add text with word wrapping and page breaks
      const addText = (text: string, fontSize: number, isBold: boolean = false, color: number[] = [0, 0, 0], lineHeight: number = 1.5) => {
        pdf.setFontSize(fontSize);
        pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
        pdf.setTextColor(color[0], color[1], color[2]);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const lineHeightMm = fontSize * 0.352778 * lineHeight;

        for (const line of lines) {
          if (yPosition + lineHeightMm > pageHeight - margin) {
            pdf.addPage();
            yPosition = margin;
            
            // Add subtle footer on new page
            pdf.setFontSize(8);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(150, 150, 150);
            pdf.text('Generated by TalkNotes', pageWidth / 2, pageHeight - 10, { align: 'center' });
          }

          pdf.text(line, margin, yPosition);
          yPosition += lineHeightMm;
        }
      };

      // Helper to add spacing
      const addSpacing = (space: number) => {
        yPosition += space;
        if (yPosition > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin;
        }
      };

      // Helper to add a subtle divider
      const addDivider = () => {
        addSpacing(3);
        pdf.setDrawColor(220, 220, 220);
        pdf.setLineWidth(0.2);
        pdf.line(margin, yPosition, pageWidth - margin, yPosition);
        addSpacing(3);
      };

      // Get the conversation mode from the document
      const inferMode = () => {
        const summaryLower = summary.toLowerCase();
        if (summaryLower.includes('📌') || summaryLower.includes('decision')) return 'Meeting';
        if (summaryLower.includes('candidate') || summaryLower.includes('interview')) return 'Interview';
        if (summaryLower.includes('objection') || summaryLower.includes('sales')) return 'Sales';
        if (summaryLower.includes('coaching') || summaryLower.includes('therapy')) return 'Coaching';
        if (summaryLower.includes('lecture') || summaryLower.includes('concept')) return 'Lecture';
        return 'Casual';
      };

      const mode = inferMode();
      const today = new Date();
      const dateStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

      // --- HEADER ---
      addText('TalkNotes', 18, true, [52, 201, 143]);
      addSpacing(2);
      addText(`${mode} Notes`, 14, true, [60, 60, 60]);
      addSpacing(1);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(120, 120, 120);
      pdf.text(dateStr, margin, yPosition);
      if (language && language !== 'Original') {
        pdf.text(`  •  ${language}`, margin + 30, yPosition);
      }
      addSpacing(4);
      
      addDivider();

      // --- KEY TAKEAWAYS ---
      addText('Key Takeaways', 13, true, [40, 40, 40]);
      addSpacing(4);

      const keyPoints = extractKeyPoints(summary);
      if (keyPoints.length > 0) {
        for (const point of keyPoints.slice(0, 10)) {
          // Draw subtle bullet
          pdf.setFillColor(52, 201, 143);
          pdf.circle(margin + 1.5, yPosition - 1.5, 1, 'F');
          
          // Add point text with indent
          const prevY = yPosition;
          pdf.setFontSize(10);
          pdf.setFont('helvetica', 'normal');
          pdf.setTextColor(50, 50, 50);
          const lines = pdf.splitTextToSize(point, contentWidth - 8);
          
          for (let i = 0; i < lines.length; i++) {
            if (yPosition + 5 > pageHeight - margin) {
              pdf.addPage();
              yPosition = margin;
            }
            pdf.text(lines[i], margin + 6, yPosition);
            yPosition += 5;
          }
          
          addSpacing(2);
        }
      } else {
        addText('No key takeaways extracted.', 10, false, [120, 120, 120]);
      }

      addSpacing(4);
      addDivider();

      // --- FULL TRANSCRIPT ---
      addText('Full Transcript', 13, true, [40, 40, 40]);
      addSpacing(4);

      // Add transcript with good line height
      addText(transcript || 'No transcript available.', 10, false, [50, 50, 50], 1.6);

      addSpacing(8);
      addDivider();

      // --- AI ANALYSIS ---
      addText('AI Analysis', 13, true, [40, 40, 40]);
      addSpacing(4);
      addText(summary || 'No analysis available.', 10, false, [50, 50, 50], 1.6);

      // --- FOOTER ---
      addSpacing(10);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(150, 150, 150);
      const footerText = `Generated by TalkNotes  •  ${today.toLocaleString('en-US', { 
        year: 'numeric', 
        month: 'short', 
        day: 'numeric', 
        hour: '2-digit', 
        minute: '2-digit' 
      })}`;
      pdf.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });

      // Save with meaningful filename
      const filename = `TalkNotes_${mode}_${today.toISOString().split('T')[0]}.pdf`;
      pdf.save(filename);
      
      console.log('✅ PDF exported successfully');
    } catch (error) {
      console.error('PDF export error:', error);
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      alert(`Failed to export PDF: ${errorMsg}`);
    } finally {
      setIsExporting(false);
    }
  };

  const exportToJPG = async () => {
    if (!documentRef.current) {
      alert('Document not ready. Please try again.');
      return;
    }
    setIsExporting(true);

    try {
      console.log('Starting JPG export...');
      const canvas = await html2canvas(documentRef.current, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#FFFFFF',
        logging: false,
        foreignObjectRendering: false,
        onclone: (clonedDoc) => {
          // Remove all stylesheets and style tags
          const styles = clonedDoc.querySelectorAll('style, link[rel="stylesheet"]');
          styles.forEach(style => style.remove());
          
          // Override ALL element styles to prevent oklch colors
          const allElements = clonedDoc.querySelectorAll('*');
          allElements.forEach((el: Element) => {
            if (el instanceof HTMLElement) {
              el.style.borderColor = 'rgb(229, 231, 235)';
              el.style.outlineColor = 'rgb(229, 231, 235)';
            }
          });
          
          console.log('Processed', allElements.length, 'elements in clone');
        },
      });

      console.log('Canvas created:', canvas.width, 'x', canvas.height);
      
      canvas.toBlob((blob) => {
        if (blob) {
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = `TalkNotes-${new Date().toISOString().split('T')[0]}.jpg`;
          link.click();
          URL.revokeObjectURL(url);
          console.log('✅ JPG exported successfully');
          alert('JPG exported successfully!');
          setIsExporting(false);
        } else {
          alert('Failed to create image. Please try again.');
          setIsExporting(false);
        }
      }, 'image/jpeg', 0.95);
    } catch (error) {
      console.error('JPG export error:', error);
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      alert(`Failed to export JPG: ${errorMsg}`);
      setIsExporting(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div className="bg-[#111418] rounded-2xl w-full max-w-6xl max-h-[90vh] overflow-hidden flex flex-col border border-[#3F4448]/50 shadow-2xl">
        {/* Header */}
        <div className="p-6 border-b border-[#3F4448]/50 flex items-center justify-between bg-gradient-to-r from-[#0B0D10] to-[#111418]">
          <div>
            <h2 className="text-2xl font-bold text-[#F2F3F2]">Document & Analysis</h2>
            <p className="text-sm text-[#9BA3A0] mt-1">Review insights, charts, and export your notes</p>
          </div>
          <button
            onClick={onClose}
            className="text-[#9BA3A0] hover:text-[#F2F3F2] transition-colors p-2 hover:bg-[#3F4448]/30 rounded-lg"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Document Preview */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '24px', backgroundColor: '#0B0D10' }}>
          <div 
            ref={documentRef}
            style={{ 
              backgroundColor: '#FFFFFF',
              borderRadius: '12px',
              padding: '48px',
              maxWidth: '800px',
              margin: '0 auto',
              minHeight: '600px',
              color: '#000000',
              fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
              boxSizing: 'border-box',
              isolation: 'isolate',
              border: 'none',
              borderColor: '#E5E7EB',
              outlineColor: '#E5E7EB'
            }}
          >
            {/* Header */}
            <div style={{ marginBottom: '32px', paddingBottom: '24px', borderBottom: '2px solid #E5E7EB' }}>
              <h1 style={{ fontSize: '36px', fontWeight: 'bold', color: '#111827', marginBottom: '8px' }}>
                TalkNotes
              </h1>
              <p style={{ fontSize: '14px', color: '#6B7280' }}>
                {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
              </p>
              {language && language !== 'Original' && (
                <div style={{ 
                  display: 'inline-block', 
                  marginTop: '16px',
                  padding: '8px 16px', 
                  backgroundColor: '#10B981', 
                  color: 'white', 
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: '600'
                }}>
                  {language}
                </div>
              )}
            </div>

            {/* Stats */}
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(3, 1fr)', 
              gap: '16px',
              marginBottom: '32px',
              padding: '16px',
              backgroundColor: '#F9FAFB',
              borderRadius: '8px'
            }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#10B981' }}>{wordCount}</div>
                <div style={{ fontSize: '11px', color: '#6B7280', textTransform: 'uppercase' }}>Words</div>
              </div>
              <div style={{ textAlign: 'center', borderLeft: '1px solid #E5E7EB', borderRight: '1px solid #E5E7EB' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#3B82F6' }}>{readTime}</div>
                <div style={{ fontSize: '11px', color: '#6B7280', textTransform: 'uppercase' }}>Min Read</div>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#8B5CF6' }}>{keyPoints.length}</div>
                <div style={{ fontSize: '11px', color: '#6B7280', textTransform: 'uppercase' }}>Key Points</div>
              </div>
            </div>

            {/* Conversation Analysis */}
            <div style={{ marginBottom: '32px', padding: '24px', backgroundColor: '#FAFAFA', borderRadius: '12px', border: '2px solid #E5E7EB' }}>
              <h2 style={{ fontSize: '24px', fontWeight: 'bold', color: '#111827', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ fontSize: '20px' }}>📊</span> Conversation Analysis
              </h2>

              {/* Comprehension Score Chart */}
              <div style={{ marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <span style={{ fontSize: '14px', fontWeight: '600', color: '#374151' }}>Comprehension Score</span>
                  <span style={{ fontSize: '18px', fontWeight: 'bold', color: comprehensionScore >= 80 ? '#10B981' : comprehensionScore >= 60 ? '#F59E0B' : '#EF4444' }}>
                    {comprehensionScore}%
                  </span>
                </div>
                <div style={{ width: '100%', height: '24px', backgroundColor: '#E5E7EB', borderRadius: '12px', overflow: 'hidden' }}>
                  <div style={{ 
                    width: `${comprehensionScore}%`, 
                    height: '100%', 
                    background: comprehensionScore >= 80 ? 'linear-gradient(90deg, #10B981, #059669)' : comprehensionScore >= 60 ? 'linear-gradient(90deg, #F59E0B, #D97706)' : 'linear-gradient(90deg, #EF4444, #DC2626)',
                    borderRadius: '12px',
                    transition: 'width 0.3s'
                  }}></div>
                </div>
                <p style={{ fontSize: '12px', color: '#6B7280', marginTop: '4px' }}>
                  {comprehensionScore >= 80 ? 'Excellent clarity and structure' : comprehensionScore >= 60 ? 'Good clarity with minor complexity' : 'Complex structure may need simplification'}
                </p>
              </div>

              {/* Conversation Lapses */}
              <div style={{ marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <span style={{ fontSize: '14px', fontWeight: '600', color: '#374151' }}>Conversation Lapses</span>
                  <span style={{ fontSize: '18px', fontWeight: 'bold', color: '#3B82F6' }}>{conversationLapses}</span>
                </div>
                <div style={{ display: 'flex', gap: '4px', alignItems: 'center' }}>
                  {[...Array(5)].map((_, i) => (
                    <div key={i} style={{ 
                      flex: 1, 
                      height: '32px', 
                      backgroundColor: i < conversationLapses ? '#3B82F6' : '#E5E7EB',
                      borderRadius: '4px'
                    }}></div>
                  ))}
                </div>
                <p style={{ fontSize: '12px', color: '#6B7280', marginTop: '4px' }}>
                  Brief pauses or incomplete thoughts detected
                </p>
              </div>

              {/* Pain Points */}
              {painPoints.length > 0 && (
                <div>
                  <h3 style={{ fontSize: '16px', fontWeight: '600', color: '#374151', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span>⚠️</span> Identified Pain Points
                  </h3>
                  {painPoints.map((point, idx) => (
                    <div key={idx} style={{ 
                      padding: '12px',
                      marginBottom: '8px',
                      backgroundColor: '#FEF3C7',
                      borderLeft: '4px solid #F59E0B',
                      borderRadius: '4px'
                    }}>
                      <p style={{ fontSize: '13px', color: '#78350F', lineHeight: '1.5' }}>{point}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Key Takeaways - Only green checkmarks */}
            <div style={{ marginBottom: '32px' }}>
              <h2 style={{ fontSize: '24px', fontWeight: 'bold', color: '#111827', marginBottom: '16px' }}>
                Key Takeaways
              </h2>
              
              {/* Key Points */}
              {keyPoints.map((point, idx) => (
                <div key={idx} style={{ 
                  display: 'flex',
                  gap: '12px',
                  padding: '12px',
                  marginBottom: '8px',
                  backgroundColor: '#ECFDF5',
                  borderLeft: '4px solid #10B981',
                  borderRadius: '4px'
                }}>
                  <span style={{ color: '#10B981', fontWeight: 'bold', fontSize: '18px' }}>✓</span>
                  <p style={{ color: '#374151', lineHeight: '1.6', flex: 1 }}>{point}</p>
                </div>
              ))}
            </div>

            {/* Transcript */}
            <div style={{ marginBottom: '32px' }}>
              <h2 style={{ fontSize: '24px', fontWeight: 'bold', color: '#111827', marginBottom: '16px' }}>
                Full Transcript
              </h2>
              <div style={{ 
                backgroundColor: '#EFF6FF',
                padding: '24px',
                borderRadius: '12px',
                border: '1px solid #DBEAFE'
              }}>
                <p style={{ color: '#374151', lineHeight: '1.8', whiteSpace: 'pre-wrap' }}>
                  {transcript}
                </p>
              </div>
            </div>

            {/* Footer */}
            <div style={{ 
              marginTop: '48px',
              paddingTop: '24px',
              borderTop: '2px solid #E5E7EB',
              textAlign: 'center'
            }}>
              <p style={{ fontSize: '12px', color: '#6B7280' }}>
                Generated by TalkNotes • {new Date().toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 border-t border-[#3F4448]/50 flex justify-end bg-gradient-to-br from-[#0B0D10] via-[#111418] to-[#0F1115]">
          <div className="relative">
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              disabled={isExporting}
              className="export-button"
            >
              <svg 
                className="export-icon" 
                width="18" 
                height="18" 
                viewBox="0 0 24 24" 
                fill="none" 
                stroke="currentColor" 
                strokeWidth="1.5"
                strokeLinecap="round" 
                strokeLinejoin="round"
              >
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              <span>{isExporting ? 'Exporting...' : 'Export document'}</span>
            </button>

            {showExportMenu && !isExporting && (
              <div className="export-menu" ref={menuRef}>
                <button
                  onClick={() => handleExportClick('pdf')}
                  className="export-menu-item"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                    <polyline points="14 2 14 8 20 8" />
                  </svg>
                  <span>Export as PDF</span>
                </button>
                <button
                  onClick={() => handleExportClick('jpg')}
                  className="export-menu-item"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                    <circle cx="8.5" cy="8.5" r="1.5" />
                    <polyline points="21 15 16 10 5 21" />
                  </svg>
                  <span>Export as JPG</span>
                </button>
              </div>
            )}

            <style jsx>{`
              .export-button {
                display: flex;
                align-items: center;
                gap: 10px;
                padding: 12px 20px;
                background: transparent;
                border: 1px solid rgba(255, 255, 255, 0.1);
                border-radius: 10px;
                color: rgba(255, 255, 255, 0.75);
                font-size: 14px;
                font-weight: 500;
                cursor: pointer;
                transition: all 200ms cubic-bezier(0.4, 0, 0.2, 1);
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
                letter-spacing: -0.01em;
              }

              .export-button:hover:not(:disabled) {
                background: rgba(255, 255, 255, 0.03);
                border-color: rgba(52, 201, 143, 0.25);
                color: rgba(255, 255, 255, 0.9);
              }

              .export-button:disabled {
                opacity: 0.5;
                cursor: not-allowed;
              }

              .export-icon {
                flex-shrink: 0;
                color: rgba(52, 201, 143, 0.7);
                transition: color 200ms ease;
              }

              .export-button:hover:not(:disabled) .export-icon {
                color: rgba(52, 201, 143, 0.9);
              }

              .export-menu {
                position: absolute;
                bottom: calc(100% + 8px);
                right: 0;
                background: rgba(17, 20, 24, 0.98);
                border: 1px solid rgba(255, 255, 255, 0.1);
                border-radius: 10px;
                padding: 6px;
                min-width: 180px;
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
                backdrop-filter: blur(12px);
                animation: menuSlideUp 200ms cubic-bezier(0.4, 0, 0.2, 1);
                z-index: 10;
              }

              @keyframes menuSlideUp {
                from {
                  opacity: 0;
                  transform: translateY(8px);
                }
                to {
                  opacity: 1;
                  transform: translateY(0);
                }
              }

              .export-menu-item {
                width: 100%;
                display: flex;
                align-items: center;
                gap: 10px;
                padding: 10px 12px;
                background: transparent;
                border: none;
                border-radius: 6px;
                color: rgba(255, 255, 255, 0.75);
                font-size: 14px;
                font-weight: 400;
                text-align: left;
                cursor: pointer;
                transition: all 150ms cubic-bezier(0.4, 0, 0.2, 1);
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
              }

              .export-menu-item:hover {
                background: rgba(52, 201, 143, 0.08);
                color: rgba(52, 201, 143, 0.95);
              }

              .export-menu-item svg {
                flex-shrink: 0;
                opacity: 0.7;
              }

              .export-menu-item:hover svg {
                opacity: 1;
              }

              @media (prefers-color-scheme: light) {
                .export-button {
                  border-color: rgba(0, 0, 0, 0.1);
                  color: rgba(0, 0, 0, 0.75);
                }

                .export-button:hover:not(:disabled) {
                  background: rgba(0, 0, 0, 0.02);
                  border-color: rgba(52, 201, 143, 0.3);
                  color: rgba(0, 0, 0, 0.9);
                }

                .export-icon {
                  color: rgba(30, 142, 94, 0.7);
                }

                .export-button:hover:not(:disabled) .export-icon {
                  color: rgba(30, 142, 94, 0.9);
                }

                .export-menu {
                  background: rgba(255, 255, 255, 0.98);
                  border-color: rgba(0, 0, 0, 0.1);
                }

                .export-menu-item {
                  color: rgba(0, 0, 0, 0.75);
                }

                .export-menu-item:hover {
                  background: rgba(30, 142, 94, 0.08);
                  color: rgba(30, 142, 94, 0.95);
                }
              }
            `}</style>
          </div>
        </div>
      </div>
    </div>
  );
}
